spring:
  profiles: dev  
  security:
    user:
      name: "user"
      password: "user"
  
hosuk:
  aaa: 'dev aaaaaaaaaaaaaaaaaaa'
  
external:
  uri: 'sdfasdfasdfasdf'

---

spring:
  profiles: real
  security:
    user:
      name: "user"
      password: "user"  
  
hosuk:
  aaa: 'real'
