spring:
  profiles: dev  
  security:
    user:
      name: "user"
      password: "user"
  

server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: "refresh"  

hosuk:
  aaa: 'dev aaaaaaaaaaaaaaaaaaa'
  
external:
  uri: 'sdfasdfasdfasdf'

---

spring:
  profiles: real
  security:
    user:
      name: "user"
      password: "user"  
  
management:
  endpoints:
    web:
      exposure:
        include: "refresh"  
  
server:
  port: 8888

hosuk:
  aaa: 'real'
