spring:
  profiles: dev

server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: "refresh"  

hosuk:
  aaa: 'dev ㅠㅠㅠㅠㅠㅠ'

---

spring:
  profiles: real
  
management:
  endpoints:
    web:
      exposure:
        include: "refresh"  
  
server:
  port: 8888

hosuk:
  aaa: 'real'
