external:
  daou:
    uri: https://sdfasdfasd
    port: 8080
    name: daou_configserver_dev_devbranch123123123123
  zlgoon:
    uri: http://zlgoon/asdfadsf
    port: 9090
    name: daou_configserver_dev
  kiwoom: daou_configserver_dev
